import type { LocationSpot } from "./types";

/**
 * The 10 featured Istanbul shoot locations. Written for organic search
 * relevance (Istanbul wedding photographer/videographer, pre-wedding &
 * couple photoshoot Istanbul) while staying editorial, not keyword-stuffed.
 */
export const locations: LocationSpot[] = [
  {
    id: "galata",
    slug: "galata",
    name: { en: "Galata", fa: "گالاتا", tr: "Galata" },
    description: {
      en: "Cobblestone streets, the iconic Galata Tower, and a skyline that mixes old and new — Galata is one of the most requested backdrops for couple photoshoots and pre-wedding photography in Istanbul.",
      fa: "کوچه‌های سنگ‌فرش، برج نمادین گالاتا و خط آسمانی که قدیم و جدید را در هم می‌آمیزد — گالاتا یکی از پرتقاضاترین لوکیشن‌ها برای عکاسی کاپل و عکاسی پره‌وداد در استانبول است.",
      tr: "Taş döşeli sokaklar, ikonik Galata Kulesi ve eskiyle yeniyi harmanlayan bir silüet — Galata, İstanbul'da çift çekimi ve pre-wedding fotoğrafçılığı için en çok talep edilen lokasyonlardan biridir.",
    },
    mood: {
      en: "Romantic, historic, effortlessly photogenic at any hour.",
      fa: "رومانتیک، تاریخی و در هر ساعتی از روز فوق‌العاده عکس‌پذیر.",
      tr: "Romantik, tarihi ve günün her saatinde fotojenik.",
    },
    image: "/images/locations/galata/galata-01.jpg",
    imageAlt: {
      en: "Galata Tower and the surrounding cobblestone streets of Istanbul",
      fa: "برج گالاتا و کوچه‌های سنگ‌فرش اطراف آن در استانبول",
      tr: "Galata Kulesi ve çevresindeki taş döşeli sokaklar",
    },
    bestTime: { en: "Golden Hour (5–7 PM)", fa: "ساعت طلایی (۵ تا ۷ بعدازظهر)", tr: "Altın Saat (17.00–19.00)" },
    crowdLevel: "medium",
    outfitSuggestion: {
      en: "Warm earth tones, deep burgundy, soft cream. Avoid black.",
      fa: "رنگ‌های گرم خاکی، زرشکی تیره، کرم ملایم. از مشکی پرهیز کنید.",
      tr: "Sıcak toprak tonları, koyu bordo, yumuşak krem. Siyahtan kaçının.",
    },
    estimatedDuration: { en: "2–3 hours", fa: "۲ تا ۳ ساعت", tr: "2–3 saat" },
    samplePhotos: [
      "/images/locations/galata/galata-02.jpg",
      "/images/locations/galata/galata-03.jpg",
      "/images/locations/galata/galata-04.jpg",
      "/images/locations/galata/galata-05.jpg",
      "/images/locations/galata/galata-06.jpg",
      "/images/locations/galata/galata-07.jpg",
    ],
    photoSpots: {
      en: [
        "Galata Bridge",
        "Under Galata Bridge",
        "Karaköy Pier",
        "Bankalar Caddesi",
        "Serdar-ı Ekrem Caddesi",
        "Around Galata Tower",
        "Schneidertempel (Terziler Synagogue)",
      ],
      fa: [
        "پل گالاتا",
        "زیر پل گالاتا",
        "اسکله کاراکوی",
        "خیابان بانکالار",
        "خیابان سردار اکرم",
        "اطراف برج گالاتا",
        "کنیسه شنایدرتمپل (ترزیلر)",
      ],
      tr: [
        "Galata Köprüsü",
        "Galata Köprüsü Altı",
        "Karaköy İskelesi",
        "Bankalar Caddesi",
        "Serdar-ı Ekrem Caddesi",
        "Galata Kulesi Çevresi",
        "Schneidertempel / Terziler Sinagogu",
      ],
    },
  },
  {
    id: "karakoy",
    slug: "karakoy",
    name: { en: "Karaköy", fa: "کاراکوی", tr: "Karaköy" },
    description: {
      en: "Once a working harbor, now Istanbul's most stylish waterfront district — Karaköy pairs industrial-chic architecture with sweeping views across the water, ideal for editorial-style wedding and couple sessions.",
      fa: "منطقه‌ای که زمانی بندری کاری بود و امروز شیک‌ترین محله ساحلی استانبول به‌شمار می‌رود — کاراکوی معماری صنعتی-شیک را با چشم‌اندازهای گسترده به آب ترکیب می‌کند و برای جلسات عکاسی عروسی و کاپل با حس‌وحال ادیتوریال ایده‌آل است.",
      tr: "Bir zamanlar çalışan bir liman olan Karaköy, şimdi İstanbul'un en şık sahil semti — endüstriyel-şık mimariyi suya açılan geniş manzaralarla birleştirerek editoryal tarzda düğün ve çift çekimleri için idealdir.",
    },
    mood: {
      en: "Urban, modern, quietly cinematic.",
      fa: "شهری، مدرن و آرام‌آرام سینمایی.",
      tr: "Kentsel, modern ve sessizce sinematik.",
    },
    image: "/images/locations/karakoy/karakoy-01.jpg",
    imageAlt: {
      en: "Karaköy waterfront district in Istanbul at dusk",
      fa: "محله ساحلی کاراکوی در استانبول هنگام غروب",
      tr: "Akşamüstü İstanbul Karaköy sahil semti",
    },
    bestTime: {
      en: "Late afternoon (4–6 PM)",
      fa: "اواخر بعدازظهر (۴ تا ۶ عصر)",
      tr: "Öğleden sonra geç saatler (16.00–18.00)",
    },
    crowdLevel: "medium",
    outfitSuggestion: {
      en: "Sleek neutrals, navy, camel, monochrome looks suit the industrial-chic backdrop.",
      fa: "رنگ‌های خاکستری شیک، سرمه‌ای، کاراملی و لوک‌های یک‌رنگ با پس‌زمینه صنعتی-شیک هماهنگ‌اند.",
      tr: "Şık nötr tonlar, lacivert, camel, monokrom görünümler endüstriyel-şık arka planla uyumludur.",
    },
    estimatedDuration: { en: "1.5–2.5 hours", fa: "۱.۵ تا ۲.۵ ساعت", tr: "1,5–2,5 saat" },
    samplePhotos: [
      "/images/locations/karakoy/karakoy-02.jpg",
      "/images/locations/karakoy/karakoy-03.jpg",
      "/images/locations/karakoy/karakoy-04.jpg",
    ],
  },
  {
    id: "bosphorus",
    slug: "bosphorus",
    name: { en: "Bosphorus", fa: "بسفر", tr: "Boğaz" },
    description: {
      en: "No location says \"Istanbul\" quite like the Bosphorus. Its waterfront promenades and golden-hour light make it a signature setting for wedding photography and films across the city.",
      fa: "هیچ لوکیشنی به‌اندازه بسفر نماد استانبول نیست. پیاده‌روهای ساحلی و نور ساعت طلایی آن، این مکان را به یک لوکیشن شاخص برای عکاسی و فیلم‌برداری عروسی در سراسر شهر تبدیل کرده است.",
      tr: "Hiçbir lokasyon Boğaz kadar 'İstanbul' demez. Sahil yürüyüş yolları ve gün batımı ışığı, onu şehrin dört bir yanındaki düğün fotoğrafçılığı ve filmleri için imza bir mekan haline getiriyor.",
    },
    mood: {
      en: "Sweeping, golden, timeless.",
      fa: "گسترده، طلایی و بی‌زمان.",
      tr: "Geniş, altın rengi ve zamansız.",
    },
    image: "/images/locations/location-bosphorus.svg",
    imageAlt: {
      en: "Wide view of the Bosphorus strait in Istanbul at golden hour",
      fa: "نمای گسترده‌ای از بسفر در استانبول در ساعت طلایی",
      tr: "Gün batımında İstanbul Boğazı'nın geniş görünümü",
    },
    bestTime: {
      en: "Sunrise (6–8 AM) or Sunset (6–8 PM)",
      fa: "طلوع (۶ تا ۸ صبح) یا غروب (۶ تا ۸ عصر)",
      tr: "Gün doğumu (06.00–08.00) veya gün batımı (18.00–20.00)",
    },
    crowdLevel: "medium",
    outfitSuggestion: {
      en: "White, navy, soft blue, sand beige. Avoid dark heavy colors.",
      fa: "سفید، سرمه‌ای، آبی ملایم، بژ شنی. از رنگ‌های تیره و سنگین پرهیز کنید.",
      tr: "Beyaz, lacivert, yumuşak mavi, kum beji. Koyu ve ağır renklerden kaçının.",
    },
    estimatedDuration: { en: "2–4 hours", fa: "۲ تا ۴ ساعت", tr: "2–4 saat" },
  },
  {
    id: "ortakoy",
    slug: "ortakoy",
    name: { en: "Ortaköy", fa: "اورتاکوی", tr: "Ortaköy" },
    description: {
      en: "The domes of Ortaköy Mosque framed against the Bosphorus Bridge create one of Istanbul's most recognizable wedding photography backdrops, especially in the soft light of early evening.",
      fa: "گنبدهای مسجد اورتاکوی در قاب پل بسفر، یکی از شناخته‌شده‌ترین پس‌زمینه‌های عکاسی عروسی در استانبول را می‌سازد، به‌خصوص در نور ملایم اوایل عصر.",
      tr: "Ortaköy Camii'nin kubbeleri Boğaz Köprüsü'nü çevreleyerek, özellikle akşamüstünün yumuşak ışığında, İstanbul'un en tanınan düğün fotoğrafçılığı fonlarından birini oluşturuyor.",
    },
    mood: {
      en: "Iconic, elegant, postcard-cinematic.",
      fa: "نمادین، شیک و سینمایی همچون یک کارت‌پستال.",
      tr: "İkonik, zarif ve kartpostal gibi sinematik.",
    },
    image: "/images/locations/location-ortakoy.svg",
    imageAlt: {
      en: "Ortaköy Mosque with the Bosphorus Bridge in the background",
      fa: "مسجد اورتاکوی با پل بسفر در پس‌زمینه",
      tr: "Arka planda Boğaz Köprüsü ile Ortaköy Camii",
    },
    bestTime: {
      en: "Late afternoon (4–6 PM)",
      fa: "اواخر بعدازظهر (۴ تا ۶ عصر)",
      tr: "Öğleden sonra geç saatler (16.00–18.00)",
    },
    crowdLevel: "medium",
    outfitSuggestion: {
      en: "Soft romantic colors — blush, ivory, soft gold. Avoid neon.",
      fa: "رنگ‌های رمانتیک ملایم — رنگ پوست، ایوری، طلایی ملایم. از نئون پرهیز کنید.",
      tr: "Yumuşak romantik renkler — pudra pembe, ivory, yumuşak altın. Neondan kaçının.",
    },
    estimatedDuration: { en: "1.5–2.5 hours", fa: "۱.۵ تا ۲.۵ ساعت", tr: "1,5–2,5 saat" },
  },
  {
    id: "balat",
    slug: "balat",
    name: { en: "Balat", fa: "بالات", tr: "Balat" },
    description: {
      en: "Pastel-colored houses, narrow alleys and decades of layered history make Balat a favorite for couples who want a more colorful, storybook feel to their pre-wedding photoshoot in Istanbul.",
      fa: "خانه‌های رنگی، کوچه‌های باریک و لایه‌های تاریخی چنددهه‌ای، بالات را به یکی از مکان‌های محبوب برای زوج‌هایی تبدیل کرده که می‌خواهند عکاسی پره‌وداد آن‌ها در استانبول حس‌وحالی رنگی و قصه‌مانند داشته باشد.",
      tr: "Pastel renkli evler, dar sokaklar ve katmanlı bir tarih — Balat, pre-wedding çekimlerinde daha renkli ve masalsı bir his isteyen çiftlerin gözdesi.",
    },
    mood: {
      en: "Colorful, nostalgic, full of character.",
      fa: "رنگارنگ، نوستالژیک و پر از شخصیت.",
      tr: "Renkli, nostaljik ve karakter dolu.",
    },
    image: "/images/locations/location-balat.svg",
    imageAlt: {
      en: "Colorful historic houses lining a narrow street in Balat, Istanbul",
      fa: "خانه‌های تاریخی رنگی در یک کوچه باریک در بالات، استانبول",
      tr: "Balat'ta dar bir sokakta renkli tarihi evler",
    },
    bestTime: { en: "Morning (8–11 AM)", fa: "صبح (۸ تا ۱۱ صبح)", tr: "Sabah (08.00–11.00)" },
    crowdLevel: "low",
    outfitSuggestion: {
      en: "Bold colors: red, yellow, cobalt blue. Patterns work well here.",
      fa: "رنگ‌های جسورانه: قرمز، زرد، آبی کبالت. الگوها و طرح‌ها هم در این لوکیشن جواب می‌دهند.",
      tr: "Cesur renkler: kırmızı, sarı, kobalt mavi. Desenler burada iyi çalışır.",
    },
    estimatedDuration: { en: "2–3 hours", fa: "۲ تا ۳ ساعت", tr: "2–3 saat" },
  },
  {
    id: "sultanahmet",
    slug: "sultanahmet",
    name: { en: "Sultanahmet", fa: "سلطان‌احمد", tr: "Sultanahmet" },
    description: {
      en: "Home to Istanbul's most iconic skyline of domes and minarets, Sultanahmet offers a grand, historic setting for couples who want their wedding photography to feel timeless and monumental.",
      fa: "سلطان‌احمد که میزبان نمادین‌ترین خط آسمان استانبول با گنبدها و مناره‌هایش است، فضایی بزرگ و تاریخی برای زوج‌هایی فراهم می‌کند که می‌خواهند عکاسی عروسی‌شان حسی بی‌زمان و باشکوه داشته باشد.",
      tr: "İstanbul'un kubbeler ve minarelerden oluşan en ikonik silüetine ev sahipliği yapan Sultanahmet, düğün fotoğraflarının zamansız ve anıtsal hissetmesini isteyen çiftler için büyük ve tarihi bir mekan sunuyor.",
    },
    mood: {
      en: "Grand, historic, unmistakably Istanbul.",
      fa: "باشکوه، تاریخی و بی‌اشتباه استانبولی.",
      tr: "Anıtsal, tarihi ve tartışmasız İstanbul.",
    },
    image: "/images/locations/location-sultanahmet.svg",
    imageAlt: {
      en: "Domes and minarets of the Sultanahmet skyline in Istanbul",
      fa: "گنبدها و مناره‌های خط آسمان سلطان‌احمد در استانبول",
      tr: "İstanbul Sultanahmet silüetindeki kubbeler ve minareler",
    },
    bestTime: {
      en: "Early morning (7–9 AM) or golden hour",
      fa: "اوایل صبح (۷ تا ۹ صبح) یا ساعت طلایی",
      tr: "Sabahın erken saatleri (07.00–09.00) veya altın saat",
    },
    crowdLevel: "high",
    outfitSuggestion: {
      en: "Rich, regal tones — deep burgundy, gold, ivory. Avoid clashing with the domes' warm stone color.",
      fa: "رنگ‌های غنی و سلطنتی — زرشکی تیره، طلایی، ایوری. از تضاد ناهماهنگ با رنگ گرم سنگ گنبدها پرهیز کنید.",
      tr: "Zengin, asil tonlar — koyu bordo, altın, ivory. Kubbelerin sıcak taş rengiyle çarpışan tonlardan kaçının.",
    },
    estimatedDuration: { en: "2–3 hours", fa: "۲ تا ۳ ساعت", tr: "2–3 saat" },
  },
  {
    id: "pierre-loti",
    slug: "pierre-loti",
    name: { en: "Pierre Loti Hill", fa: "تپه پیرلوتی", tr: "Pierre Loti Tepesi" },
    description: {
      en: "Reached by cable car above the Golden Horn, Pierre Loti Hill offers sweeping panoramic views that are especially striking at sunset — a quieter, more intimate choice for couple sessions.",
      fa: "تپه پیرلوتی که با تله‌کابین بر فراز شاخ طلایی قرار دارد، چشم‌اندازهای پانورامای گسترده‌ای را ارائه می‌دهد که به‌خصوص هنگام غروب آفتاب خیره‌کننده است — انتخابی آرام‌تر و خصوصی‌تر برای جلسات عکاسی کاپل.",
      tr: "Haliç'in üzerinde teleferikle ulaşılan Pierre Loti Tepesi, özellikle gün batımında etkileyici panoramik manzaralar sunar — çift çekimleri için daha sakin ve samimi bir seçim.",
    },
    mood: {
      en: "Elevated, peaceful, made for golden hour.",
      fa: "مرتفع، آرام و ساخته‌شده برای ساعت طلایی.",
      tr: "Yüksek, sakin ve gün batımı için yaratılmış.",
    },
    image: "/images/locations/location-pierre-loti.svg",
    imageAlt: {
      en: "Panoramic view of the Golden Horn from Pierre Loti Hill at sunset",
      fa: "چشم‌انداز پانورامای شاخ طلایی از تپه پیرلوتی هنگام غروب",
      tr: "Gün batımında Pierre Loti Tepesi'nden Haliç'in panoramik görünümü",
    },
    bestTime: {
      en: "Sunrise or late afternoon",
      fa: "طلوع آفتاب یا اواخر بعدازظهر",
      tr: "Gün doğumu veya öğleden sonra geç saatler",
    },
    crowdLevel: "low",
    outfitSuggestion: {
      en: "Earthy tones, terracotta, olive, warm browns. Flowy fabrics.",
      fa: "رنگ‌های خاکی، تراکوتا، زیتونی، قهوه‌ای گرم. پارچه‌های روان و سبک.",
      tr: "Toprak tonları, terracotta, zeytin yeşili, sıcak kahverengiler. Akışkan kumaşlar.",
    },
    estimatedDuration: { en: "1.5–2.5 hours", fa: "۱.۵ تا ۲.۵ ساعت", tr: "1,5–2,5 saat" },
  },
  {
    id: "rooftop-luxury-yacht",
    slug: "rooftop-luxury-yacht",
    name: {
      en: "Rooftops, Luxury Hotels & Yachts",
      fa: "روفتاپ، هتل‌های لوکس و قایق‌های اختصاصی",
      tr: "Çatı Katları, Lüks Oteller & Yatlar",
    },
    description: {
      en: "For couples who want the city skyline as their backdrop without the crowds, rooftop terraces, luxury hotel suites and private yachts on the Bosphorus offer an elevated, editorial setting for wedding and couple photography.",
      fa: "برای زوج‌هایی که می‌خواهند خط آسمان شهر را به‌عنوان پس‌زمینه داشته باشند، بدون ازدحام جمعیت — تراس‌های روفتاپ، سوییت‌های هتل‌های لوکس و قایق‌های خصوصی روی بسفر، فضایی والا و ادیتوریال برای عکاسی عروسی و کاپل فراهم می‌کنند.",
      tr: "Kalabalıktan uzak, şehir silüetini arka plan olarak isteyen çiftler için çatı katı terasları, lüks otel süitleri ve Boğaz'da özel yatlar, düğün ve çift fotoğrafçılığı için sofistike, editoryal bir ortam sunar.",
    },
    mood: {
      en: "Exclusive, polished, effortlessly luxurious.",
      fa: "اختصاصی، شیک و لوکس بدون تلاش اضافی.",
      tr: "Ayrıcalıklı, zarif ve zahmetsizce lüks.",
    },
    image: "/images/locations/location-rooftop-yacht.svg",
    imageAlt: {
      en: "Private rooftop terrace overlooking the Istanbul skyline at night",
      fa: "تراس خصوصی روفتاپ با چشم‌اندازی به خط آسمان استانبول در شب",
      tr: "Gece İstanbul silüetine bakan özel çatı katı terası",
    },
    bestTime: {
      en: "Golden hour or after dark for the skyline lights",
      fa: "ساعت طلایی یا بعد از تاریک‌شدن هوا برای نورهای خط آسمان",
      tr: "Altın saat veya gece ışıkları için hava karardıktan sonra",
    },
    crowdLevel: "low",
    outfitSuggestion: {
      en: "Full luxury styling — champagne, deep gold, emerald, midnight blue.",
      fa: "استایل کاملاً لوکس — شامپاینی، طلایی تیره، زمردی، سرمه‌ای نیمه‌شب.",
      tr: "Tam lüks stil — şampanya rengi, koyu altın, zümrüt, gece lacivert.",
    },
    estimatedDuration: { en: "2–3 hours", fa: "۲ تا ۳ ساعت", tr: "2–3 saat" },
  },
  {
    id: "grand-hotel-de-londres",
    slug: "grand-hotel-de-londres",
    name: {
      en: "Grand Hotel de Londres",
      fa: "گرند هتل دو لندر",
      tr: "Grand Hotel de Londres",
    },
    description: {
      en: "A 19th-century boutique hotel in Pera, Grand Hotel de Londres is loved by photographers for its faded grandeur — gilded mirrors, antique furniture, caged birds and candlelit staircases. Its bohemian, vintage interiors make it one of Istanbul's most cinematic indoor settings for wedding photography, in any season and regardless of weather.",
      fa: "هتل بوتیک گرند هتل دو لندر، با قدمتی از قرن نوزدهم در محله پرا، در میان عکاسان به‌خاطر شکوه نوستالژیک خود شناخته شده است — آینه‌های طلاکوب، مبلمان عتیقه، قفس‌های پرنده و راه‌پله‌هایی در نور شمع. فضای داخلی بوهمیایی و وینتیج آن، این هتل را به یکی از سینمایی‌ترین لوکیشن‌های سرپوشیده استانبول برای عکاسی عروسی تبدیل کرده، در هر فصل و بدون نگرانی از آب‌وهوا.",
      tr: "Pera'da 19. yüzyıldan kalma butik bir otel olan Grand Hotel de Londres (Büyük Londra Oteli), yaldızlı aynaları, antika mobilyaları, kuş kafesleri ve mum ışığıyla aydınlanan merdivenleriyle fotoğrafçılar arasında nostaljik zarafetiyle tanınır. Bohem ve vintage iç mekanları, onu İstanbul'un mevsimden ve hava koşulundan bağımsız en sinematik kapalı mekan düğün fotoğrafçılığı lokasyonlarından biri yapar.",
    },
    mood: {
      en: "Antique, bohemian, unmistakably nostalgic.",
      fa: "عتیقه‌ای، بوهمیایی و غرق در نوستالژی.",
      tr: "Antika, bohem ve nostaljik bir zarafet.",
    },
    image: "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-01.jpg",
    imageAlt: {
      en: "Bride and groom on the antique staircase of Grand Hotel de Londres in Istanbul",
      fa: "عروس و داماد روی راه‌پله عتیقه گرند هتل دو لندر در استانبول",
      tr: "İstanbul'daki Grand Hotel de Londres'in antika merdivenlerinde gelin ve damat",
    },
    bestTime: {
      en: "Any time — fully indoors, weather-independent",
      fa: "هر زمانی — کاملاً سرپوشیده و مستقل از آب‌وهوا",
      tr: "Her zaman — tamamen kapalı mekan, hava koşulundan bağımsız",
    },
    crowdLevel: "low",
    outfitSuggestion: {
      en: "Antique-inspired tones: deep wine, emerald, ivory lace. Avoid bright modern neons that clash with the vintage decor.",
      fa: "رنگ‌های الهام‌گرفته از عتیقه: شرابی تیره، زمردی، توری ایوری. از نئون‌های مدرن روشن که با دکور وینتیج ناهماهنگ‌اند پرهیز کنید.",
      tr: "Antika esintili tonlar: koyu şarap rengi, zümrüt, ivory dantel. Vintage dekorla çelişen parlak modern neonlardan kaçının.",
    },
    estimatedDuration: { en: "2–3 hours", fa: "۲ تا ۳ ساعت", tr: "2–3 saat" },
    samplePhotos: [
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-02.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-03.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-04.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-05.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-06.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-07.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-08.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-09.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-10.jpg",
      "/images/locations/grand-hotel-de-londres/grand-hotel-de-londres-11.jpg",
    ],
  },
  {
    id: "galata-bridge",
    slug: "galata-bridge",
    name: {
      en: "Galata Bridge (Eminönü)",
      fa: "پل گالاتا (امینونو)",
      tr: "Galata Köprüsü (Eminönü)",
    },
    description: {
      en: "Where the Golden Horn meets the Bosphorus, Galata Bridge's lower deck — lined with fish restaurants and framed by its distinctive iron archways — opens onto postcard views of the Galata Tower skyline on one side and the domes of Süleymaniye Mosque on the other. Few spots pack more of Istanbul into a single frame.",
      fa: "جایی که شاخ طلایی به بسفر می‌رسد، طبقه پایین پل گالاتا — با رستوران‌های ماهی‌فروشی و طاق‌های آهنی متمایزش — به چشم‌اندازی همچون کارت‌پستال از خط آسمان برج گالاتا از یک سو و گنبدهای مسجد سلیمانیه از سوی دیگر باز می‌شود. کمتر جایی این‌قدر از استانبول را در یک قاب جمع می‌کند.",
      tr: "Haliç'in Boğaz'la buluştuğu noktada, balık restoranlarıyla dolu ve kendine özgü demir kemerleriyle çevrili Galata Köprüsü'nün alt katı — bir yanda Galata Kulesi silüetine, diğer yanda Süleymaniye Camii'nin kubbelerine açılan kartpostallık manzaralar sunar. Çok az yer İstanbul'u tek bir karede bu kadar yoğun barındırır.",
    },
    mood: {
      en: "Lively, golden, unmistakably Istanbul on the water.",
      fa: "پرجنب‌وجوش، طلایی و بی‌اشتباه استانبولی بر روی آب.",
      tr: "Hareketli, altın rengi ve su üzerinde tartışmasız İstanbul.",
    },
    image: "/images/locations/galata-bridge/galata-bridge-01.jpg",
    imageAlt: {
      en: "Bride and groom on Galata Bridge with the Galata Tower skyline behind them at golden hour",
      fa: "عروس و داماد روی پل گالاتا با خط آسمان برج گالاتا در پس‌زمینه، در ساعت طلایی",
      tr: "Altın saatte Galata Köprüsü'nde, arka planda Galata Kulesi silüetiyle gelin ve damat",
    },
    bestTime: {
      en: "Sunset (6–8 PM)",
      fa: "غروب آفتاب (۶ تا ۸ عصر)",
      tr: "Gün batımı (18.00–20.00)",
    },
    crowdLevel: "high",
    outfitSuggestion: {
      en: "Classic black tie and ivory lace or satin gowns work beautifully against the warm stone and iron tones. Avoid neon brights that clash with the bridge's blue ironwork.",
      fa: "کت‌وشلوار کلاسیک مشکی و لباس‌های توری یا ساتن ایوری با تن‌رنگ‌های گرم سنگ و آهن بسیار هماهنگ‌اند. از رنگ‌های نئون که با فلز آبی پل ناهماهنگ‌اند پرهیز کنید.",
      tr: "Klasik siyah takım ve ivory dantel veya saten gelinlikler, sıcak taş ve demir tonlarıyla muhteşem uyum sağlar. Köprünün mavi demir işçiliğiyle çarpışan neon renklerden kaçının.",
    },
    estimatedDuration: { en: "2–3 hours", fa: "۲ تا ۳ ساعت", tr: "2–3 saat" },
    samplePhotos: [
      "/images/locations/galata-bridge/galata-bridge-02.jpg",
      "/images/locations/galata-bridge/galata-bridge-03.jpg",
      "/images/locations/galata-bridge/galata-bridge-04.jpg",
      "/images/locations/galata-bridge/galata-bridge-05.jpg",
      "/images/locations/galata-bridge/galata-bridge-06.jpg",
      "/images/locations/galata-bridge/galata-bridge-07.jpg",
      "/images/locations/galata-bridge/galata-bridge-08.jpg",
      "/images/locations/galata-bridge/galata-bridge-09.jpg",
      "/images/locations/galata-bridge/galata-bridge-10.jpg",
      "/images/locations/galata-bridge/galata-bridge-11.jpg",
      "/images/locations/galata-bridge/galata-bridge-12.jpg",
      "/images/locations/galata-bridge/galata-bridge-13.jpg",
      "/images/locations/galata-bridge/galata-bridge-14.jpg",
      "/images/locations/galata-bridge/galata-bridge-15.jpg",
      "/images/locations/galata-bridge/galata-bridge-16.jpg",
      "/images/locations/galata-bridge/galata-bridge-17.jpg",
    ],
  },
];

export function getLocationBySlug(slug: string): LocationSpot | undefined {
  return locations.find((location) => location.slug === slug);
}
